### PR TITLE
Update build image to 1.23.3.

### PR DESCRIPTION
**Pull request by mattdurham**
Update the build image to 1.23

### CODE REVIEW

**Review by wildum — COMMENTED** [review]
I think that you also need to update the version in .github/workflows/check-linux-build-image.yml and there is also a comment is tools/build-image/Dockerfile about the version

**Comment by mattdurham** [comment]
Good call on the workflow, what comment are you referring to?

**Comment by wildum** [comment]
> Good call on the workflow, what comment are you referring to?

https://github.com/grafana/alloy/blob/main/tools/build-image/Dockerfile#L7

**Comment by wildum** [comment]
ah but it's only relevant for the next PR actually

**Pull request merged**
