### PR TITLE
Add alias for common URL mistake in get started section

### PR DESCRIPTION
**Pull request by clayton-cornell**
#### PR Description
Add alias for common URL mistake in get started section
#### PR Checklist

- [ ] CHANGELOG.md updated
- [ ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Review by jdbaldry — COMMENTED** [review]
It works to redirect /docs/alloy/latest/getting_started/ for example. Is the common typo usually with an underscore instead of a dash?

Where do we often see this mistake?

**Comment by clayton-cornell** [comment]
There's been a few cases now of people using the path `/docs/alloy/latest/getting_started/` instead of `/docs/alloy/latest/get-started/`  possibly because the topic title is (currently) **Getting started**.

**Comment by clayton-cornell** [comment]
@jdbaldry Is this worth doing in your view? Or close and move on? :-)

**Comment by jdbaldry** [comment]
I think it's worthwhile if people are commonly going there, I guess I was just a bit surprised that it's underscore separated and not dash separated path elements that people are typing in.

Unless they aren't typing it and instead it's coming from somewhere else like an old page location or a typo'd link somewhere

**Comment by clayton-cornell** [comment]
It's just something that's popped up a couple of times... typos mainly in blogs and external references. If you can approve, I'll get it through and we have another PR done :-)

**Review by jdbaldry — APPROVED** [review]

**Pull request merged**
