### PR TITLE
Change `path` to `filename`

### PR DESCRIPTION
**Pull request by mehuman**
As per https://grafana.com/docs/alloy/latest/reference/components/local.file/

#### PR Description
Updating the example to match the docs. Verified with a working example.

#### PR Checklist

- [ ] CHANGELOG.md updated
- [X ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Review by clayton-cornell — APPROVED** [review]
Nice catch, Thanks for putting this PR through

**Comment by clayton-cornell** [comment]
@mehuman When you have a chance, can you sign the CLA so we can finalize this PR :-)

**Comment by clayton-cornell** [comment]
@mehuman Just pinging you again here to ask if you can sign the CLA so we can get this PR merged :-)

**Comment by mehuman** [comment]
Just signed. Sorry for the delay!

**Comment by clayton-cornell** [comment]
I made the changes in a newer PR https://github.com/grafana/alloy/pull/1403 because I wanted to get this fix through.  Now that you've signed the CLA, all of your new PRs will be ready to go much sooner.

I'll close this PR since the fix is already in place. Please keep the PRs coming. Even a small change helps the community :-)

**Pull request closed without merging**
