### PR TITLE
Cherrypick for v1.2.1

### PR DESCRIPTION
**Pull request by mattdurham**
Cherry pick 266e5e09ca5dc1b089b01e2e84a7d13bf305f98e c, 5cf8a4a278d8c78f2ead883aa214ce366ea480a3 , d225ad3 and 5f382fc3c3183238aed1dd4bb14369bb34b1983a  .

### CODE REVIEW

**Comment by rfratto** [comment]
Is there a reason we're not cherry picking over the other bugfixes in main?

**Comment by mattdurham** [comment]
They weren't mentioned when I asked, but I can if we want.

**Comment by mattdurham** [comment]
Both look small so I will pull them in.

**Comment by mattdurham** [comment]
Other bugs pulled in.

**Review by rfratto — APPROVED** [review]

**Pull request merged**
