### PR TITLE
chore(pyroscope): mark pyroscope components as GA

### PR DESCRIPTION
**Pull request by korniltsev**
#### PR Description

Dealing with stability-preview is a burden for both internal grafana users and external.
Let's mark `pyroscope.ebpf`, `pyroscope.java`, `pyroscope.scrape`, `pyroscope.write`, `discovery.process` as GA.

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

### CODE REVIEW

**Review by simonswine — APPROVED** [review]
LGTM Either that. I probably would even argue that the default stability-level for Alloy should be "public-preview"

**Comment by korniltsev** [comment]
Let's wait for more approves from @rfratto @tpaschalis @petethepig @Rperry2174

**Comment by rfratto** [comment]
I don’t think we should mark components GA because it’s a burden. If the components are stable, are ready for production use, and they won’t have any breaking changes, then they qualify for GA. Are they at that state yet?

**Comment by rfratto** [comment]
For reference, GA means these two things: 

* It follows the definitions of the [Grafana Labs release cycle](https://grafana.com/docs/release-life-cycle/)
* [Breaking changes will no longer happen in minor releases](https://grafana.com/docs/alloy/latest/introduction/backward-compatibility/)

While not documented, we also are trying to aim to release a new major version no more frequently than yearly. 

I’m comfortable with this PR being merged if these components are ready, but I want to make sure the implications are known first.

**Review by Rperry2174 — APPROVED** [review]
Discussed with the team and also agree that we meet the GA criteria! 👍

**Review by rfratto — APPROVED** [review]
Given the above, I'm on board 👍

**Review by clayton-cornell — APPROVED** [review]

**Pull request merged**
