### PR TITLE
add hostAliases to helm chart

### PR DESCRIPTION
**Pull request by duncan485**
#### Notes to the Reviewer
I'd like to be able to add hostAliases to the pod. Any feedback is welcome 

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [? ] Config converters updated

### CODE REVIEW

**Comment by wildum** [comment]
@petewall another helm chart PR

**Review by petewall — APPROVED** [review]
Looks reasonable to me

**Comment by duncan485** [comment]
hey @wildum I see there is still a test failing, is there anything I can do about it ? I'm not sure it's related to the Chart.

**Review by wildum — APPROVED** [review]

**Comment by wildum** [comment]
> hey @wildum I see there is still a test failing, is there anything I can do about it ? I'm not sure it's related to the Chart.

Hey sorry about that, this seems to be a flaky test from an experimental WAL feature that we are testing. As long as the tests run in drone then we are fine, it's not a blocker for this PR

**Comment by wildum** [comment]
Merged! Thanks again for the contribution!

**Pull request merged**
